= CompuLab Devices BSP

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir compulab-bsp
$: cd compulab-bsp
$: repo init -u https://github.com/compulab-yokneam/compulab-bsp -b krogoth
$: repo sync

At the end of the commands you have every metadata you need to start work with.

*To start a cm-fx6-evk evaluation image build:*

[source,console]
$: MACHINE=cm-fx6-evk source ./setup-environment build
$: bitbake compulab-eval-image

*To build kernel only:*

[source,console]
$: bitbake linux-compulab

*To build U-Boot only:*

[source,console]
$: bitbake u-boot-compulab

You can use any directory to host your build. The source code is checked out at `compulab-bsp/sources`.

*How to Deploy:*
[%hardbreaks]
To deploy the image file to an sdcard, issue this command. 
Assuming the sdcard device file is *_/dev/sdg_*

[source,console]
$: xz -dc tmp/deploy/images/cm-fx6-evk/compulab-eval-image-cm-fx6-evk.tar.xz | sudo dd of=/dev/sdg

*How to Evaluate:*
[%hardbreaks]
* Insert the sd-card into the SB-FX6 P6 slot;
* Power up the device;
* Stop in U-Boot;
* Issue:
[%hardbreaks]
[source,console]
$: env default -a
$: savenv
$: reset
* Let the device boot up.
* Evaluate this Yocto Release.
